### ISSUE TITLE
Plan to imprement unit tests?

### ISSUE THREAD

**Issue by ajinkyapatil8190** [Nikhil-Shawn/human-resource-management-system#41]
I see a setup of folder for unittests are you planning to implement unittest? 

https://github.com/Nikhil-Shawn/human-resource-management-system/blob/development/src/test/java/main/humanresourcemanagementsystem/MainApplicationTests.java

**Comment by Nikhil-Shawn** [comment]
Yes, we will try if we have enough time

**Comment by Nikhil-Shawn** [comment]
Can I close this issue?
