### ISSUE TITLE
Remove Commented code

### ISSUE THREAD

**Issue by ajinkyapatil8190** [Nikhil-Shawn/human-resource-management-system#47]
https://github.com/Nikhil-Shawn/human-resource-management-system/blob/536d811b9caa7fff3b128c6f82dc3ff2ec142456/src/main/java/com/humanresourcemanagementsystem/Entity/Experience.java#L113

**Comment by poojasanjaypatil** [comment]
Added comments and removed commented code in the development branch for ( Asset, Benefit, Education and Experience ).

**Comment by Nikhil-Shawn** [comment]
Can I close this issue?

**Comment by ajinkyapatil8190** [comment]
There is still commented code.

![image](https://github.com/Nikhil-Shawn/human-resource-management-system/assets/13133800/de3ec835-5fdc-4eb6-b7fa-766c68c49cb1)

**Comment by poojasanjaypatil** [comment]
<img width="728" alt="Experience" src="https://github.com/Nikhil-Shawn/human-resource-management-system/assets/169813461/bee6fac7-3252-4e26-a2a4-fa232344d555">

I don't see any commented code.
Can you please re-check the development branch?

**Comment by ajinkyapatil8190** [comment]
I just did, looks good 👍
